#!/usr/bin/env python3
"""
Strategy Extractor — Strategy Generator
=========================================
Reads the latest analysis results and produces:
  1. Markdown strategy report (human-readable)
  2. JSON ruleset (machine-readable, for a trading bot)

Usage:
  python3 oat_strategy.py              # Print report to stdout
  python3 oat_strategy.py --json       # Print JSON ruleset to stdout
  python3 oat_strategy.py --save       # Save report.md + ruleset.json to disk
  python3 oat_strategy.py --telegram   # Send summary to Telegram
"""

import os
import sys
import json
import time
from datetime import datetime
from zoneinfo import ZoneInfo

import oat_db as db

EST = ZoneInfo("America/New_York")

# Telegram config
TELEGRAM_CONFIG_PATH = os.path.expanduser("~/.telegram-bot.json")


def load_telegram_config():
    try:
        with open(TELEGRAM_CONFIG_PATH) as f:
            return json.load(f)
    except Exception:
        return None


def send_telegram(message):
    cfg = load_telegram_config()
    if not cfg:
        return
    import requests
    try:
        requests.post(
            f"https://api.telegram.org/bot{cfg['token']}/sendMessage",
            json={"chat_id": cfg["chat_id"], "text": message, "parse_mode": "HTML"},
            timeout=10,
        )
    except Exception:
        pass


def get_analysis_data():
    """Get latest analysis with parsed JSON data blobs."""
    result = db.get_latest_analysis()
    if not result:
        return None
    return result


def conf_label(c):
    if c >= 0.8:
        return "HIGH"
    if c >= 0.6:
        return "MODERATE"
    if c >= 0.3:
        return "EMERGING"
    return "LOW"


def conf_bar(c, width=20):
    filled = int(c * width)
    return "█" * filled + "░" * (width - filled)


# ============================================
# MARKDOWN REPORT
# ============================================

def generate_report(analysis):
    """Generate markdown strategy report."""
    now = datetime.now(EST).strftime("%Y-%m-%d %H:%M EST")
    readiness = analysis.get("overall_readiness", 0)
    sample = analysis.get("sample_size", 0)

    lines = []
    lines.append(f"# Uncommon-Oat Strategy Report")
    lines.append(f"")
    lines.append(f"**Generated**: {now}")
    lines.append(f"**Sample size**: {sample} traded windows")
    lines.append(f"**Overall readiness**: {readiness:.0%} ({conf_label(readiness)})")
    lines.append(f"")

    if readiness >= 0.6:
        lines.append(f"> Strategy is ready for deployment. All dimensions have actionable patterns.")
    elif readiness >= 0.3:
        lines.append(f"> Strategy is emerging. Some dimensions need more data. Check back after more observations.")
    else:
        lines.append(f"> Not enough data. Keep the observer running to accumulate more windows.")
    lines.append(f"")
    lines.append(f"---")

    dims = [
        ("1. Entry Timing", "entry_timing", "⏱️"),
        ("2. Side Selection", "side_selection", "🎯"),
        ("3. Pricing", "pricing", "💰"),
        ("4. Sizing", "sizing", "📊"),
        ("5. Arb Structure", "arb_structure", "🔗"),
        ("6. Exit Behavior", "exit_behavior", "🚪"),
    ]

    for title, key, icon in dims:
        conf_key = f"{key}_confidence"
        data_key = f"{key}_data"
        conf = analysis.get(conf_key, 0)
        data = analysis.get(data_key, {})
        if isinstance(data, str):
            data = json.loads(data)

        lines.append(f"")
        lines.append(f"## {icon} {title}")
        lines.append(f"")
        lines.append(f"**Confidence**: {conf:.0%} ({conf_label(conf)}) `[{conf_bar(conf)}]`")
        lines.append(f"")

        rule = data.get("rule", "Insufficient data")
        lines.append(f"**Rule**: {rule}")
        lines.append(f"")

        # Key metrics
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        for k, v in data.items():
            if k in ("confidence", "sample_size", "rule"):
                continue
            if isinstance(v, dict):
                for kk, vv in v.items():
                    lines.append(f"| {kk} | {vv} |")
            elif isinstance(v, float):
                lines.append(f"| {k} | {v:.4f} |")
            else:
                lines.append(f"| {k} | {v} |")

    lines.append(f"")
    lines.append(f"---")
    lines.append(f"")
    lines.append(f"*Generated by OAT Strategy Extractor*")

    return "\n".join(lines)


# ============================================
# JSON RULESET
# ============================================

def generate_ruleset(analysis):
    """Generate machine-readable JSON ruleset for a trading bot."""
    now = datetime.now(EST).isoformat()
    readiness = analysis.get("overall_readiness", 0)
    sample = analysis.get("sample_size", 0)

    rules = {}

    # Entry Timing
    et = analysis.get("entry_timing_data", {})
    if isinstance(et, str):
        et = json.loads(et)
    if et.get("confidence", 0) > 0:
        median = et.get("median_offset")
        stdev = et.get("std_dev", 0)
        if median is not None:
            enter_after = max(0, int(median - stdev))
            enter_before = min(900, int(median + stdev))
            rules["entry_timing"] = {
                "enter_after_secs": enter_after,
                "enter_before_secs": enter_before,
                "median_offset_secs": int(median),
                "remaining_at_entry": 900 - int(median),
                "confidence": round(et.get("confidence", 0), 3),
            }

    # Side Selection
    ss = analysis.get("side_selection_data", {})
    if isinstance(ss, str):
        ss = json.loads(ss)
    if ss.get("confidence", 0) > 0:
        pcts = ss.get("first_side_pcts", {})
        dominant = max(pcts, key=pcts.get) if pcts else None
        rules["side_selection"] = {
            "default_first_side": dominant,
            "first_side_pcts": pcts,
            "confidence": round(ss.get("confidence", 0), 3),
        }
        # Add conditional rules if available
        conditionals = ss.get("conditional_probs", {})
        if conditionals:
            conditions = []
            for bucket, probs in conditionals.items():
                dom_side = max(probs, key=probs.get) if probs else None
                if dom_side and probs[dom_side] > 0.6:
                    conditions.append({
                        "if": f"ob_bucket == '{bucket}'",
                        "then": f"buy {dom_side} first",
                        "probability": round(probs[dom_side], 3),
                    })
            if conditions:
                rules["side_selection"]["conditions"] = conditions

    # Pricing
    pr = analysis.get("pricing_data", {})
    if isinstance(pr, str):
        pr = json.loads(pr)
    if pr.get("confidence", 0) > 0:
        rules["pricing"] = {
            "up_avg_price": round(pr.get("up_avg_price", 0), 4),
            "down_avg_price": round(pr.get("down_avg_price", 0), 4),
            "maker_ratio": round(pr.get("maker_ratio", 0), 2),
            "execution_style": "MAKER" if pr.get("maker_ratio", 0) > 60 else "TAKER",
            "confidence": round(pr.get("confidence", 0), 3),
        }

    # Sizing
    sz = analysis.get("sizing_data", {})
    if isinstance(sz, str):
        sz = json.loads(sz)
    if sz.get("confidence", 0) > 0:
        rules["sizing"] = {
            "avg_usdc_per_window": round(sz.get("avg_usdc", 0), 2),
            "avg_shares_per_window": round(sz.get("avg_shares", 0), 1),
            "sizing_type": sz.get("sizing_type", "UNKNOWN"),
            "coefficient_of_variation": round(sz.get("coefficient_of_variation", 0), 3),
            "confidence": round(sz.get("confidence", 0), 3),
        }

    # Arb Structure
    arb = analysis.get("arb_structure_data", {})
    if isinstance(arb, str):
        arb = json.loads(arb)
    if arb.get("confidence", 0) > 0:
        rules["arb_structure"] = {
            "both_sides": arb.get("both_sides_rate", 0) > 0.5,
            "both_sides_rate": round(arb.get("both_sides_rate", 0), 3),
            "median_leg_gap_secs": arb.get("median_leg_gap"),
            "median_combined_cost": arb.get("median_combined_cost"),
            "first_leg_dominant": arb.get("first_leg_dominant"),
            "confidence": round(arb.get("confidence", 0), 3),
        }

    # Exit Behavior
    ex = analysis.get("exit_behavior_data", {})
    if isinstance(ex, str):
        ex = json.loads(ex)
    if ex.get("confidence", 0) > 0:
        rules["exit_behavior"] = {
            "strategy": ex.get("exit_strategy", "UNKNOWN"),
            "sell_rate": round(ex.get("sell_rate", 0), 3),
            "confidence": round(ex.get("confidence", 0), 3),
        }

    return {
        "version": "1.0",
        "generated_at": now,
        "sample_size": sample,
        "overall_readiness": round(readiness, 3),
        "rules": rules,
    }


# ============================================
# CLI
# ============================================

def main():
    db.init_db()
    analysis = get_analysis_data()

    if not analysis:
        print("No analysis results yet. Run the observer to accumulate data.")
        sys.exit(1)

    args = sys.argv[1:]

    if "--json" in args:
        ruleset = generate_ruleset(analysis)
        print(json.dumps(ruleset, indent=2))

    elif "--save" in args:
        report = generate_report(analysis)
        ruleset = generate_ruleset(analysis)

        report_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "oat_report.md")
        ruleset_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "oat_ruleset.json")

        with open(report_path, "w") as f:
            f.write(report)
        with open(ruleset_path, "w") as f:
            json.dump(ruleset, f, indent=2)

        print(f"Report saved to: {report_path}")
        print(f"Ruleset saved to: {ruleset_path}")

    elif "--telegram" in args:
        readiness = analysis.get("overall_readiness", 0)
        sample = analysis.get("sample_size", 0)

        msg = f"<b>OAT STRATEGY UPDATE</b>\n"
        msg += f"Readiness: {readiness:.0%} ({conf_label(readiness)})\n"
        msg += f"Sample: {sample} windows\n\n"

        dims = [
            ("Entry Timing", "entry_timing_confidence"),
            ("Side Selection", "side_selection_confidence"),
            ("Pricing", "pricing_confidence"),
            ("Sizing", "sizing_confidence"),
            ("Arb Structure", "arb_structure_confidence"),
            ("Exit Behavior", "exit_behavior_confidence"),
        ]
        for name, key in dims:
            c = analysis.get(key, 0)
            msg += f"  {name}: {c:.0%}\n"

        send_telegram(msg)
        print("Telegram notification sent.")

    else:
        # Default: print markdown report
        report = generate_report(analysis)
        print(report)


if __name__ == "__main__":
    main()
